# BTEC (fr -> en) baseline

learning_rate_decay_factor: 0.95
dropout_rate: 0.5
cell_size: 256
embedding_size: 256
layers: 2
bidir: True
use_lstm: True
steps_per_checkpoint: 500
steps_per_eval: 2000
max_steps: 50000

data_dir: data/btec
model_dir: models/baseline
# log_file: models/baseline/log.txt
num_samples: 0

optimizer: 'adam'
learning_rate: 0.001
initial_state_attention: True

encoders:
  - name: fr
    vocab_size: 9218

decoder:
    name: en
    vocab_size: 7186
