# Really small model on BTEC for debugging purposes

dropout_rate: 0.0
cell_size: 64
attn_size: 64
embedding_size: 32

layers: 1
bidir: True
use_lstm: False
steps_per_checkpoint: 200
steps_per_eval: 200
max_output_len: 25
max_input_len: 25
weight_scale: 0.1

data_dir: data/btec
model_dir: models/btec_reinforce
log_file: models/btec_reinforce/log.txt
batch_size: 32
dev_prefix: dev
max_dev_size: 500

max_gradient_norm: 1.0
optimizer: 'sgd'
learning_rate: 0.01
reset: True
loss_function: 'reinforce'
baseline_steps: 1000
reinforce_baseline: True
reinforce_reward: sentence_bleu
score_function: corpus_bleu

learning_rate_decay_factor: 0.9
decay_every_n_epoch: 1
decay_after_n_epoch: 5
max_epochs: 25

batch_mode: 'standard'
read_ahead: 10

encoders:
  - name: fr

decoder:
    name: en
