# Really small model on BTEC for debugging purposes

dropout_rate: 0.0
steps_per_checkpoint: 50
steps_per_eval: 100
keep_best: 1
batch_size: 16
cell_size: 128
embedding_size: 128
layers: 1
bidir: False
use_lstm: False

data_dir: data/btec_speech
model_dir: models/debug
log_file: null

encoders:
  - name: fr
    vocab_size: 9218
    buckets: [ 5, 10, 20, 50]

decoder:
    name: en
    vocab_size: 7186
    buckets: [10, 15, 25, 50]