# Really small model on BTEC for debugging purposes

dropout_rate: 0.2
steps_per_checkpoint: 100
steps_per_eval: 200
keep_best: 1
batch_size: 32
cell_size: 128
embedding_size: 128
layers: 1
bidir: True
use_lstm: True

data_dir: data/btec
model_dir: models/debug
log_file: null
dev_prefix: dev.100
max_output_len: 20
training_algorithm: 'sgd'
learning_rate: 1

encoders:
  - name: fr
    vocab_size: 9218

decoder:
    name: en
    vocab_size: 7186
