# Really small model on BTEC for debugging purposes

dropout_rate: 0.0
cell_size: 64
attn_size: 64
embedding_size: 32

layers: 1
bidir: True
use_lstm: False
steps_per_checkpoint: 200
steps_per_eval: 200
max_steps: 0
max_output_len: 25
max_input_len: 25
weight_scale: 0.1

data_dir: data/btec
model_dir: models/debug
# log_file: models/debug/log.txt
batch_size: 32
read_ahead: 10
dev_prefix: dev
max_dev_size: 500

optimizer: 'adam'
max_gradient_norm: 5.0
# baseline_steps: 2000
# optimizer: 'sgd'
# learning_rate: 0.2
# loss_function: 'reinforce'

encoders:
  - name: fr

decoder:
    name: en
