# Really small model on BTEC for debugging purposes

dropout_rate: 0.0
cell_size: 64
attn_size: 64
embedding_size: 32

layers: 1
bidir: True
use_lstm: False
steps_per_checkpoint: 200
steps_per_eval: 400
eval_burn_in: 0
max_steps: 10000
max_output_len: 25
max_input_len: 25
feed_previous: 0.0

data_dir: data/btec
model_dir: models/debug
# log_file: models/debug_SGD/log.txt
max_dev_size: 0
batch_size: 16
read_ahead: 5
dev_prefix: dev
max_dev_size: 500

optimizer: 'sgd'
learning_rate: 1.0
max_gradient_norm: 1.0

weight_scale: 0.1

encoder:
    name: fr

decoder:
    name: en
