vocab_size: [0, 405]
size: [64]
embedding_size: [123, 64]
steps_per_checkpoint: 50
steps_per_eval: 200
verbose: True
batch_size: 16
dev_prefix: dev
ext: [feats, en]
binary_input: feats
layers: 1
buckets: [200, 15]