
learning_rate_decay_factor: 0.99
dropout_rate: 0.5
bidir: True
use_lstm: True

data_dir: data/btec_speech
model_dir: models/speech_translation_2
log_file: models/speech_translation_2/log.txt

max_output_len: 25
max_input_len: 600
parallel_iterations: 32
swap_memory: True
optimizer: 'adam'
learning_rate: 0.001
# num_samples: 0

encoders:
  - name: feats
    embedding_size: 123
    vocab_size: 0
    cell_size: 256
    layers: 3
    time_pooling: [2, 2]
    pooling_avg: True
    binary: True
    attention_filters: 1
    attention_filter_length: 25
    input_layers: [256, 256]
    input_layer_size: 256
    # attention_window_size: 10

decoder:
    name: en
    vocab_size: 7186
    cell_size: 256
    embedding_size: 256
    layers: 2
