vocab_size: [0, 9218]
size: [256, 256]
embedding_size: [123, 256]
steps_per_checkpoint: 1000
steps_per_eval: 2000
batch_size: 32
dev_prefix: dev
ext: [feats, fr]
binary_input: feats
layers: [3, 2]
time_pooling: [2, 2]
buckets: [200, 15]
attention_filters: 1
attention_filter_length: 40
learning_rate_decay_factor: 0.95
dropout_rate: 0.2
bidir: True
use_lstm: True
beam_size: 1
allow_growth: True
verbose: True